

name:  expenseTracker app

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: 10

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      # Install Surge
      - name: Rebuild node sass
        run: npm rebuild node-sass@4.14.1 --force

      - name: Isntall node sass
        run: npm install --unsafe-perm -g node-sass@4.14.1

      # Runs a set of commands using the runners shell
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command

      # Install Surge
      - name: Install Surge
        run: npm install --global surge
      # Rename the index.html file to 200.html
      - name: Rename the index.html file to 200.html
        run: sudo cp ./build/index.html ./build/200.html && sudo rm ./build/index.html
      # Deploy Surge
      - name: Deploy React App to Surge
        run: surge ./build http://expensetracker-adeel.surge.sh/ --token ${{ secrets.SURGETOKEN }}

# # This is a basic workflow to help you get started with Actions

# name: expenseTracker app

# # Controls when the action will run. Triggers the workflow on push or pull request
# # events but only for the master branch
# on:
#   push:
#     branches: [master]

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       - name: Setup Node.js environment
#         uses: actions/setup-node@v2-beta
#         with:
#           version: 12
#       - name: GitHub Action for Yarn
#         uses: Borales/actions-yarn@v2.3.0
#         with:
#           # Yarn command
#           cmd: install
#       - name: creating build
#         run: yarn build
#       - name: installing surge
#         run: npm install --global surge
#       - name: deploying on surge
#         run: surge ./build http://expensetracker-adeel.surge.sh/ --token ${{ secrets.SURGETOKEN}}
